name: Flask-Selenium-CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==7.4.4 pytest-html pytest-metadata



      - name: Start Flask app
        run: |
         source .venv/bin/activate
         nohup python app/app.py &
         sleep 5

      - name: Run tests (Pytest + Selenium)
        run: |
          pip install -r requirements.txt
          pytest tests/ \
          --junitxml=reports/unit_results.xml \
          --html=reports/selenium_report.html


      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/
